id: P4C08C894
initial_creation_type: input
source_metadata:
  title: Record of Teachings Received by Gong dkar Phrin las rnam rgyals (17th cent.)
  author: གོང་དཀར་འཕྲིན་ལས་རྣམ་རྒྱལ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-01-18);
    no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by the rDzong pa'i
    dpe rnying 'tshol bsdu khang. (src)
  - Text input:རྫོང་པའི་དཔེ་རྙིང་འཚོལ་བསྡུ་ཁང་། (Tibet) (dpn)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/3131
  bases:
    bae8:
      title: Record of Teachings Received by Gong dkar Phrin las rnam rgyals (17th
        cent.)
      order: 1
      base_file: bae8.txt
created_at: '2022-04-15T19:05:41.354197'
last_modified_at: '2022-04-15T19:05:41.354205'
quality: null
